version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./news-aggregator:/var/www/html
    ports:
      - "8080:8080"
    # command: ["supervisord", "-c", "/etc/supervisord.conf"]
    command: sh -c "chown -R 1000:www-data /var/www/html /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && supervisord -c /etc/supervisord.conf"
    depends_on:
      - mysql
      - mailhog
      - redis
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: news_aggregator_db
      MYSQL_USER: news_aggregator_db_user
      MYSQL_PASSWORD: news_aggregator_db_password
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network


  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    ports:
      - "8025:8025"
    networks:
      - laravel_network

  redis:
    image: redis:6.0-alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
